service: detect-pull-request-conflict

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20211221
  environment:
    NODE_ENV: production
    APP_ID: ${param:APP_ID}
    PRIVATE_KEY: ${param:PRIVATE_KEY}
    WEBHOOK_SECRET: ${param:WEBHOOK_SECRET}

functions:
  webhooks:
    handler: index.handler
    events:
      - httpApi:
          path: /api/github/webhooks
          method: post
